# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(240, 320)
        Form.setMinimumSize(QtCore.QSize(240, 320))
        Form.setMaximumSize(QtCore.QSize(240, 320))
        self.label_Title = QtWidgets.QLabel(Form)
        self.label_Title.setGeometry(QtCore.QRect(30, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Title.setFont(font)
        self.label_Title.setObjectName("label_Title")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 201, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Zero = QtWidgets.QLabel(self.layoutWidget)
        self.label_Zero.setObjectName("label_Zero")
        self.gridLayout.addWidget(self.label_Zero, 0, 0, 1, 1)
        self.lineEdit_Zero = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_Zero.setObjectName("lineEdit_Zero")
        self.gridLayout.addWidget(self.lineEdit_Zero, 0, 1, 1, 1)
        self.label_Peak = QtWidgets.QLabel(self.layoutWidget)
        self.label_Peak.setObjectName("label_Peak")
        self.gridLayout.addWidget(self.label_Peak, 1, 0, 1, 1)
        self.lineEdit_Peak = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_Peak.setObjectName("lineEdit_Peak")
        self.gridLayout.addWidget(self.lineEdit_Peak, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 230, 181, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_Print = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_Print.setObjectName("pushButton_Print")
        self.gridLayout_3.addWidget(self.pushButton_Print, 0, 0, 1, 1)
        self.pushButton_Exit = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.gridLayout_3.addWidget(self.pushButton_Exit, 0, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(60, 181, 121, 18))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_Nyquist = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_Nyquist.setObjectName("checkBox_Nyquist")
        self.gridLayout_2.addWidget(self.checkBox_Nyquist, 0, 0, 1, 1)
        self.checkBox_Bode = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_Bode.setObjectName("checkBox_Bode")
        self.gridLayout_2.addWidget(self.checkBox_Bode, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Auto"))
        self.label_Title.setText(_translate("Form", "Auto-Control"))
        self.label_Zero.setText(_translate("Form", "零点矩阵"))
        self.label_Peak.setText(_translate("Form", "极点矩阵"))
        self.pushButton_Print.setText(_translate("Form", "绘制"))
        self.pushButton_Exit.setText(_translate("Form", "退出"))
        self.checkBox_Nyquist.setText(_translate("Form", "Nyquist"))
        self.checkBox_Bode.setText(_translate("Form", "Bode"))
